name: Jekyll Build and Deploy

    on:
      push:
        branches:
          - master # 또는 기본 브랜치 이름

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set safe directory
            run: git config --global --add safe.directory /github/workspace

          - name: Setup Ruby and Gems
            uses: ruby/setup-ruby@v1
            with:
              ruby-version: '3.0' # 또는 지원되는 Ruby 버전
              bundler-cache: true

          - name: Install Dependencies
            run: bundle install

          - name: Build with Jekyll
            run: bundle exec jekyll build

          - name: Deploy to GitHub Pages
            uses: actions/deploy-pages@v2
            with:
              artifact_name: ./_site
              folder: ./_site